// Dev 1 / EXISTING — MSG91 OTP SMS service
// Sends and (optionally) verifies OTPs via the MSG91 REST API.
// We use MSG91 only for *delivery*; the source of truth for validity
// is our own otp_codes table (otp.model.ts).

import axios, { AxiosError } from 'axios';
import { env } from '../config/env';
import { logger } from '../utils/logger';

// ── Constants ────────────────────────────────────────────────────────────────

const MSG91_BASE = 'https://api.msg91.com/api/v5';

// MSG91 requires the phone to be just digits, no "+"
// "919876543210" is the correct format (country code + number)

// ── Types ────────────────────────────────────────────────────────────────────

interface Msg91SendResponse {
  type:    string;   // "success" | "error"
  message: string;
}

interface Msg91VerifyResponse {
  type:    string;
  message: string;
}

// ── sendOtp ──────────────────────────────────────────────────────────────────

/**
 * Send a 6-digit OTP SMS via MSG91.
 *
 * In production: makes a real HTTP call to MSG91.
 * In development/test: logs the OTP to console instead of sending SMS
 *   (avoids burning SMS credits during development).
 *
 * @param phone   Normalised phone number e.g. "919876543210"
 * @param otp     Plaintext 6-digit OTP generated by generateOtp()
 */
export async function sendOtp(phone: string, otp: string): Promise<void> {
  // ── Dev/Test bypass ──────────────────────────────────────
  if (env.NODE_ENV !== 'production') {
    logger.info(`[MSG91 DEV] OTP for ${phone}: ${otp}`);
    // Print clearly so the developer can read it during local testing
    console.log(`\n  ✉  OTP → ${phone}: ${otp}\n`);
    return;
  }

  // ── Production: call MSG91 ───────────────────────────────
  try {
    const response = await axios.post<Msg91SendResponse>(
      `${MSG91_BASE}/otp`,
      {
        template_id: env.MSG91_TEMPLATE_ID,
        mobile:      phone,
        authkey:     env.MSG91_AUTH_KEY,
        otp,
      },
      {
        headers: { 'Content-Type': 'application/json' },
        timeout: 10_000,
      },
    );

    if (response.data.type !== 'success') {
      throw new Error(`MSG91 rejected OTP send: ${response.data.message}`);
    }

    logger.info('OTP SMS sent via MSG91', { phone });
  } catch (err) {
    const message = err instanceof AxiosError
      ? err.response?.data?.message ?? err.message
      : (err as Error).message;

    logger.error('Failed to send OTP via MSG91', { phone, error: message });
    throw new Error(`OTP delivery failed: ${message}`);
  }
}

// ── verifyOtpWithMsg91 ───────────────────────────────────────────────────────

/**
 * Optional: verify the OTP directly with MSG91 (useful if you want MSG91
 * to be the authoritative store rather than your own DB).
 *
 * RoundU uses its own DB as the source of truth (otp.model.ts),
 * so this function is provided for completeness but NOT called in the main flow.
 *
 * @returns true if MSG91 says the OTP is valid
 */
export async function verifyOtpWithMsg91(
  phone: string,
  otp:   string,
): Promise<boolean> {
  if (env.NODE_ENV !== 'production') {
    logger.warn('[MSG91 DEV] verifyOtpWithMsg91 skipped in non-production');
    return true;
  }

  try {
    const response = await axios.get<Msg91VerifyResponse>(
      `${MSG91_BASE}/otp/verify`,
      {
        params: {
          authkey: env.MSG91_AUTH_KEY,
          mobile:  phone,
          otp,
        },
        timeout: 10_000,
      },
    );

    return response.data.type === 'success';
  } catch (err) {
    const message = err instanceof AxiosError
      ? err.response?.data?.message ?? err.message
      : (err as Error).message;

    logger.error('MSG91 OTP verify call failed', { phone, error: message });
    return false;
  }
}

// ── generateOtp ──────────────────────────────────────────────────────────────

/**
 * Generate a cryptographically random 6-digit OTP string.
 *
 * Uses crypto.randomInt (Node 14.10+) which is CSPRNG-backed,
 * unlike Math.random().
 */
export function generateOtp(): string {
  const { randomInt } = require('crypto') as typeof import('crypto');
  // randomInt(min, max) → integer in [min, max)
  // 100000 → 999999 gives exactly 6 digits
  return randomInt(100_000, 1_000_000).toString();
}
