-- Migration 023 - TODO
-- Migration: 023_recommendations
-- Owner: Dev 3 (GPS + AI)
--
-- Stores AI-generated service recommendations surfaced to users.
-- One row per recommendation item. A single engine run may insert many rows for one user.
-- The `action` column is updated via POST /api/recommendations/feedback.

CREATE TYPE recommendation_action AS ENUM ('pending', 'clicked', 'booked', 'dismissed');

CREATE TABLE recommendations (
  id                UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID                    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_id        UUID                    NOT NULL REFERENCES services(id) ON DELETE CASCADE,

  -- Why this was recommended: human-readable string generated by vLLM
  -- e.g. "You booked AC servicing 3 months ago — summer is here again."
  reason            TEXT                    NOT NULL,

  -- Confidence score from the AI model (0.0 – 1.0). Higher = shown first.
  score             NUMERIC(4, 3)           NOT NULL DEFAULT 0.5
                    CHECK (score >= 0 AND score <= 1),

  -- Predicted date the user will need this service (ISO date, no time)
  predicted_date    DATE,

  -- Feedback captured by POST /api/recommendations/feedback
  action            recommendation_action   NOT NULL DEFAULT 'pending',
  action_recorded_at TIMESTAMPTZ,

  -- Batch tag so we can expire old runs and keep only the latest per user
  engine_run_id     UUID                    NOT NULL,

  created_at        TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

-- Primary query path: GET /api/recommendations → latest high-score items for user
CREATE INDEX idx_recommendations_user_score
  ON recommendations (user_id, score DESC, created_at DESC);

-- Used to expire previous engine runs when a new batch arrives
CREATE INDEX idx_recommendations_engine_run
  ON recommendations (engine_run_id);

-- Used by feedback endpoint
CREATE INDEX idx_recommendations_action
  ON recommendations (user_id, action);

COMMENT ON TABLE  recommendations IS 'AI-generated service recommendations per user, with feedback loop.';
COMMENT ON COLUMN recommendations.score IS 'Confidence/priority score from vLLM (0–1). Higher scores surface first.';
COMMENT ON COLUMN recommendations.engine_run_id IS 'UUID shared by all rows from a single engine invocation; used to expire old batches.';
